const SUCCESS_COLOR = '#43d787';
const FAVORITE_COLOR = '#f766ad';
const WARNING_COLOR = '#ffbb00';
const CLOSE_COLOR = '#3598DB';

export { SUCCESS_COLOR, FAVORITE_COLOR, WARNING_COLOR, CLOSE_COLOR };
